/**
* Facebook Internet Explorer Toolbar Software License 
* Copyright (c) 2009 Facebook, Inc. 
*
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (which, together with any graphical images included with such
* software, are collectively referred to below as the "Software") to (a) use,
* reproduce, display, distribute, execute, and transmit the Software, (b)
* prepare derivative works of the Software (excluding any graphical images
* included with the Software, which may not be modified or altered), and (c)
* permit third-parties to whom the Software is furnished to do so, all
* subject to the following:
*
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.  
*
* Facebook, Inc. retains ownership of the Software and all associated
* intellectual property rights.  All rights not expressly granted in this
* license are reserved by Facebook, Inc.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*/ 

#ifndef OBJECTSSERVER_H
#define OBJECTSSERVER_H

#include "../../util/StringUtils.h"

namespace facebook {

/**
 * class ObjectsServer
 *
 * Utility class used to encapsulate reference 
 * counting. It provides simple and synchronized
 * possibility to increment/decrement dll 
 * reference counting. It also provides possibility to 
 * register unregister toolbar and sidebar in registry
 */
class ObjectsServer{

   // Construction / Destruction

private:

   ObjectsServer() {}

   ~ObjectsServer() {}

   // Methods
public:
   
  /**
   * sync. increment of reference counter.
   * 
   */
   static const LONG lock();

  /**
   * sync. decrement of reference counter.
   * 
   */
   static const LONG unlock();

  /**
   * @return true if server is locked, false -
   * otherwise
   */
   static const bool isLocked();

  /**
   * Does all necessary steps to register toolbar and 
   * sidebar in registry
   * @see http://msdn.microsoft.com/en-us/library/cc144099(VS.85).aspx
   */
   static void registerServer();

  /**
   * Does all necessary steps to unregister toolbar and 
   * sidebar in registry
   * @see http://msdn.microsoft.com/en-us/library/cc144099(VS.85).aspx
   */
   static void unregisterServer();

  /**
   * @return - instance handle
   */
   static const HINSTANCE getInstanceHandle();

  /**
   * @return - instance filename
   */
   static const String getInstanceFileName();

};

} // !namespace facebook


#endif // OBJECTSSERVER_H
