/**
* Facebook Internet Explorer Toolbar Software License 
* Copyright (c) 2009 Facebook, Inc. 
*
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (which, together with any graphical images included with such
* software, are collectively referred to below as the "Software") to (a) use,
* reproduce, display, distribute, execute, and transmit the Software, (b)
* prepare derivative works of the Software (excluding any graphical images
* included with the Software, which may not be modified or altered), and (c)
* permit third-parties to whom the Software is furnished to do so, all
* subject to the following:
*
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.  
*
* Facebook, Inc. retains ownership of the Software and all associated
* intellectual property rights.  All rights not expressly granted in this
* license are reserved by Facebook, Inc.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*/ 

#include "StdAfx.h"

#include "ObjectsServer.h"
#include "ClassIds.h"
#include "RegistrationUtils.h"

#include "../../util/ModuleUtils.h"
#include "../../util/LogUtils.h"



namespace facebook{


static LONG locksCount = 0;

// ---------------------------------------------------------------------
// class ObjectsServer
// ---------------------------------------------------------------------

const LONG ObjectsServer::lock() {
  LOG4CPLUS_DEBUG(LogUtils::getLogger(), _T("ObjectsServer::lock counter = ") << locksCount);
  return InterlockedIncrementAcquire(&locksCount);
}


const LONG ObjectsServer::unlock() {
   LOG4CPLUS_DEBUG(LogUtils::getLogger(), _T("ObjectsServer::unlock counter = ") << locksCount);
   return InterlockedDecrementRelease(&locksCount);
}


void ObjectsServer::registerServer() {
  facebook::registerServer(CLSID_IESidebar, _T("Facebook Sidebar"));
  facebook::registerInCategory(CLSID_IESidebar, CATID_InfoBand);
  facebook::registerSidebar(CLSID_IESidebar, _T("Facebook Sidebar"));

  facebook::registerServer(CLSID_IEToolbar, _T("Facebook Toolbar"));
  // do not register as Communication band 
  //facebook::registerInCategory(CLSID_IEToolbar, CATID_CommBand);
  facebook::registerToolbar(CLSID_IEToolbar, _T("Facebook Toolbar"));

  facebook::deletePostSetupEntries();
}


void ObjectsServer::unregisterServer() {
  facebook::unRegisterInCategory(CLSID_IESidebar, CATID_InfoBand);
  facebook::unRegisterSidebar(CLSID_IESidebar);
  facebook::unRegisterServer(CLSID_IESidebar);

  facebook::unRegisterServer(CLSID_IEToolbar);
  facebook::unRegisterInCategory(CLSID_IEToolbar, CATID_CommBand);
  facebook::unRegisterToolbar(CLSID_IEToolbar);

  facebook::deletePostSetupEntries();
}


const HINSTANCE ObjectsServer::getInstanceHandle() {
  return AfxGetInstanceHandle();
}


const String ObjectsServer::getInstanceFileName() {
  return facebook::getModuleFileName(getInstanceHandle());
}


const bool ObjectsServer::isLocked() {
  LOG4CPLUS_DEBUG(LogUtils::getLogger(), _T("ObjectsServer::isLocked counter = ") << locksCount);
  return InterlockedCompareExchange(&locksCount, 0, 0) != 0;
}

} // !namespace facebook