/**
* Facebook Internet Explorer Toolbar Software License 
* Copyright (c) 2009 Facebook, Inc. 
*
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (which, together with any graphical images included with such
* software, are collectively referred to below as the "Software") to (a) use,
* reproduce, display, distribute, execute, and transmit the Software, (b)
* prepare derivative works of the Software (excluding any graphical images
* included with the Software, which may not be modified or altered), and (c)
* permit third-parties to whom the Software is furnished to do so, all
* subject to the following:
*
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.  
*
* Facebook, Inc. retains ownership of the Software and all associated
* intellectual property rights.  All rights not expressly granted in this
* license are reserved by Facebook, Inc.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*/ 

#ifndef REGISTRATIONUTILS_H
#define REGISTRATIONUTILS_H

#include "../../data/SessionInfo.h"

#include "../../util/StringUtils.h"
#include "../../util/RegistryUtils.h"

namespace facebook{

/**
 * registers toolbar in appropriate place in registry
 *
 * @param  classId - server class id
 * @param  title - displayed name
 * @see ObjectsServer::registerServer
 */
bool registerToolbar(const CLSID& classId, const String& title);

/**
 * registers sidebar in appropriate place in registry
 *
 * @param  classId - server in this case 
 * @param  title - displayed name
 * @see ObjectsServer::registerServer
 */
bool registerSidebar(const CLSID& classId, const String& title);


/**
 * Registers server in registry
 *
 * @param  classId - server class ID
 * @param  title - displayed name
 * @see ObjectsServer::registerServer
 */
bool registerServer(const CLSID& classId, const String& title);

/**
 * Registers server in category
 *
 * @param  classId - server class ID
 * @param  categoryId - predefined category id (e.g. CATID_InfoBand)
 * @see ObjectsServer::registerServer
 */
bool registerInCategory(const CLSID& classId, const CATID& categoryId);


bool unRegisterToolbar(const CLSID& classId);

bool unRegisterServer(const CLSID& classId);

bool unRegisterSidebar(const CLSID& classId);

bool unRegisterInCategory(const CLSID& classId, const CATID& categoryId);

/**
 *  Force IE to reload settings.
 */
void deletePostSetupEntries();

}

#endif // REGISTRYUTILS_H
