/**
* Facebook Internet Explorer Toolbar Software License 
* Copyright (c) 2009 Facebook, Inc. 
*
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (which, together with any graphical images included with such
* software, are collectively referred to below as the "Software") to (a) use,
* reproduce, display, distribute, execute, and transmit the Software, (b)
* prepare derivative works of the Software (excluding any graphical images
* included with the Software, which may not be modified or altered), and (c)
* permit third-parties to whom the Software is furnished to do so, all
* subject to the following:
*
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.  
*
* Facebook, Inc. retains ownership of the Software and all associated
* intellectual property rights.  All rights not expressly granted in this
* license are reserved by Facebook, Inc.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*/ 

#include "StdAfx.h"

#include "UpdateUrlDlg.h"

#include "../../data/ToolbarSettings.h"

#include "../../common/ResourceMessages.h"

#include "../../util/WndUtils.h"

namespace facebook{

IMPLEMENT_DYNAMIC(UpdateUrlDlg, CDialog)


BEGIN_MESSAGE_MAP(UpdateUrlDlg, CDialog)
   ON_BN_CLICKED(IDOK, &UpdateUrlDlg::OnBtnOk)
END_MESSAGE_MAP()

UpdateUrlDlg::UpdateUrlDlg(CWnd* pParent /*=NULL*/)
  : CDialog(UpdateUrlDlg::IDD, pParent) {
}

UpdateUrlDlg::~UpdateUrlDlg() {
}

BOOL UpdateUrlDlg::OnInitDialog() {
   loadData();
   return CDialog::OnInitDialog();
}

void UpdateUrlDlg::OnBtnOk() {
   saveData();
   OnOK();
}

void UpdateUrlDlg::loadData() {
  String updateUrlPrefix = 
    ToolbarSettings::getInstance().readStringValue(TO_UPDATEURLPREFIX);
  ::SetDlgItemText(GetSafeHwnd(), 
    IDC_PREFIX_EDIT, updateUrlPrefix.c_str());
}

void UpdateUrlDlg::saveData() {
  // get the editbox
  CWnd* editbox = 
    FromHandle(::GetDlgItem(GetSafeHwnd(), IDC_PREFIX_EDIT));
  if (editbox) {
    const CString text = getWindowText(*editbox);
    String updateUrlPrefix = String(text.GetString());
    ToolbarSettings::getInstance().writeValue(
      TO_UPDATEURLPREFIX, updateUrlPrefix);
    editbox->Detach();
  }
}

} //!namespace facebook