/**
* Facebook Internet Explorer Toolbar Software License 
* Copyright (c) 2009 Facebook, Inc. 
*
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (which, together with any graphical images included with such
* software, are collectively referred to below as the "Software") to (a) use,
* reproduce, display, distribute, execute, and transmit the Software, (b)
* prepare derivative works of the Software (excluding any graphical images
* included with the Software, which may not be modified or altered), and (c)
* permit third-parties to whom the Software is furnished to do so, all
* subject to the following:
*
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.  
*
* Facebook, Inc. retains ownership of the Software and all associated
* intellectual property rights.  All rights not expressly granted in this
* license are reserved by Facebook, Inc.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*/

#ifndef COMMONCONSTANTS_H
#define COMMONCONSTANTS_H

#include "../util/StringUtils.h"

namespace facebook {

// Registry path contants 
const String kFacebookUpdatesUrl = _T("http://www.facebook.com/toolbar/ie/getupdates.php?version=");

const String kToolbarSettingsRegistryPath = _T("Software\\Facebook\\IEToolbar");
const String kSessionKeyEntryName = _T("sessionKey");
const String kSessionUserIdEntryName = _T("sessionUserID");
const String kSessionExpiresEntryName = _T("sessionExpires");
const String kSessionSecretEntryName = _T("sessionSecret");
const String kClientServicePath = _T("Software\\Facebook\\FBClientService");
const String kFacebookSessionPath = kClientServicePath + _T("\\Session");

const String kFacebookUpdatesUrlPrefixName = _T("facebookUpdatesUrlPrefix");
const String kFacebookUpdateJobName = _T("Facebook Toolbar Update");
// Tooblar settings key values
// New friend request
const String kNewFriendRequest= _T("newFriendRequest"); 

// New Message
const String kNewMessage = _T("newMessage");  

// New Poke 
const String kNewPoke = _T("newPoke"); 

// New Friend 
const String kNewFriend = _T("newFriend"); 

// New Event Invite
const String kNewEventInvite = _T("newEventInvite"); 

// New group invite 
const String kNewGroupInvite = _T("newGroupInvite"); 

// New Share
const String kNewShare = _T("newShare"); 

// Someone Wrote on your wall
const String kNewSmoneWroteWall = _T("smoneWroteWall"); 

//A friend updated his/her profile
const String kFriendUpdatedProfile = _T("friendUpdatedProfile"); 

// A friend updated his/her status
const String kFriendUpdatedStatus = _T("friendUpdatedStatus"); 

//A friend updated his/her albums
const String kFriendUpdatedAlbum = _T("friendUpdatedAlbum"); 

//A friend updated his/her wall
const String kFriendUpdatedWall = _T("friendUpdatedWall"); 

// A friend wrote a note
const String kFriendWroteNote = _T("friendWroteNote"); 

// Enable Pop-up Notification
const String kPopupNotification = _T("showPopupNotification"); 


// Other options to store in registry

// Friend List Sort Mode
const String kFriendListSortMode = _T("friendListSortMode");


// current culture settings
const String kCurrentCultureId = _T("currentCultureId");
const String kIsCultureAutoDetected = _T("isCultureAutoDetected");

const String kCheckUpdates = _T("checkUpdates");
const String kUpdatesCounter = _T("updatesCounter");
const String kUpdatesTimeout = _T("updatesTimeoutHours");

const int kUpdatesTimeoutDefault = 3;

// HTML View actions
const String kNoFriendToShow = _T("");
const String kPressEnterToFindFriend = _T("s.php_%s");
const String kSeeAllFriends = _T("allFriends");
const String kPleaseLogin = _T("login_fakeid");
const String kLoadingFriendsList = _T("");

// Internet Explorer process
const String kIeProcessName = _T("iexplore.exe");

const int kCookiesSize = 4096;

const int kMaxUpdatesTries = 3;
} // !namespace facebook

#endif