/**
* Facebook Internet Explorer Toolbar Software License 
* Copyright (c) 2009 Facebook, Inc. 
*
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (which, together with any graphical images included with such
* software, are collectively referred to below as the "Software") to (a) use,
* reproduce, display, distribute, execute, and transmit the Software, (b)
* prepare derivative works of the Software (excluding any graphical images
* included with the Software, which may not be modified or altered), and (c)
* permit third-parties to whom the Software is furnished to do so, all
* subject to the following:
*
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.  
*
* Facebook, Inc. retains ownership of the Software and all associated
* intellectual property rights.  All rights not expressly granted in this
* license are reserved by Facebook, Inc.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*/

#ifndef LANGCONSTANTS_H
#define LANGCONSTANTS_H

#include "../util/StringUtils.h"

namespace facebook {

// Constants that are used for localisation

const int kMaxCultures = 1000;
const int kDefaultCultureResource = 45000;
const String kCultureName = _T("languageName");

const String kFacebookToolbar = _T("facebookToolbar");
// toolbar settings dialog
const String kSettingsConfigureTheFacebookToolbar = _T("settingsConfigureTheFacebookToolbar");
const String kSettingsEnablePopUpNotification = _T("settingsEnablePopUpNotification");
const String kSettingsNotificationAboutMe = _T("settingsNotificationAboutMe");
const String kSettingsNewFriendRequest = _T("settingsNewFriendRequest");
const String kSettingsNewMessage = _T("settingsNewMessage");
const String kSettingsNewPoke = _T("settingsNewPoke");
const String kSettingsNewFriend = _T("settingsNewFriend");
const String kSettingsNewEventInvite = _T("settingsNewEventInvite");
const String kSettingsNewGroupInvite = _T("settingsNewGroupInvite");
const String kSettingsNewShare = _T("settingsNewShare");
const String kSettingsSomeoneWroteOnYourWall = _T("settingsSomeoneWroteOnYourWall");
const String kSettingsNotificationAboutMyFriends = _T("settingsNotificationAboutMyFriends");
const String kSettingsAFriendUpdatedHisHerProfile = _T("settingsAFriendUpdatedHisHerProfile");
const String kSettingsAFriendUpdatedHisHerStatus = _T("settingsAFriendUpdatedHisHerStatus");
const String kSettingsAFriendUpdatedHisHerAlbums = _T("settingsAFriendUpdatedHisHerAlbums");
const String kSettingsAFriendUpdatedHisHerWall = _T("settingsAFriendUpdatedHisHerWall");
const String kSettingsAFriendWroteANote = _T("settingsAFriendWroteANote");
const String kSettingsCheckForUpdates = _T("settingsCheckForUpdates");

const String kButtonOk = _T("buttonOk");
const String kButtonCancel = _T("buttonCancel");
const String kButtonYes = _T("buttonYes");
const String kButtonNo = _T("buttonNo");

// sidebar
const String kSidebarFacebookSidebar = _T("sidebarFacebookSidebar");
const String kSidebarSettings = _T("sidebarSettings");
const String kSidebarSortingByLastUpdate = _T("sidebarSortingByLastUpdate");
const String kSidebarSortingByStatus = _T("sidebarSortingByStatus");
const String kSidebarSortingByProfile = _T("sidebarSortingByProfile");
const String kSidebarSortingByName = _T("sidebarSortingByName");
const String kSidebarMenuLastUpdateTime = _T("sidebarMenuLastUpdateTime");
const String kSidebarMenuStatusUpdateTime = _T("sidebarMenuStatusUpdateTime");
const String kSidebarMenuProfileUpdateTime = _T("sidebarMenuProfileUpdateTime");
const String kSidebarMenuName = _T("sidebarMenuName");

//toolbar
const String kToolbarButtonQuickLinks = _T("toolbarButtonQuickLinks");
const String kToolbarButtonLoginToFacebook = _T("toolbarButtonLoginToFacebook");
const String kToolbarButtonLogout = _T("toolbarButtonLogout");
const String kToolbarButtonShare = _T("toolbarButtonShare");

const String kToolbarSearchFacebook = _T("toolbarSearchFacebook");
const String kToolbarSetYourStatus = _T("toolbarSetYourStatus");
const String kToolbarStatusPrefix = _T("toolbarStatusPrefix");
const String kToolbarHintFacebookFriendsSidebar = _T("toolbarHintFacebookFriendsSidebar");
const String kToolbarHintFacebookQuickLinks = _T("toolbarHintFacebookQuickLinks");
const String kToolbarHintGoToFacebook = _T("toolbarHintGoToFacebook");
const String kToolbarHintNewPokes = _T("toolbarHintNewPokes");
const String kToolbarHintNewFriendRequests = _T("toolbarHintNewFriendRequests");
const String kToolbarHintNewMessages = _T("toolbarHintNewMessages");
const String kToolbarHintNewEventInviations = _T("toolbarHintNewEventInviations");
const String kToolbarHintNewGroupInvitations = _T("toolbarHintNewGroupInvitations");
const String kToolbarHintShareCurrentPageOnFacebook = _T("toolbarHintShareCurrentPageOnFacebook");
const String kToolbarHintLoginToFacebook = _T("toolbarHintLoginToFacebook");
const String kToolbarHintLogoutFromFacebook = _T("toolbarHintLogoutFromFacebook");

const String kToolbarMenuProfile = _T("toolbarMenuProfile");
const String kToolbarMenuFriends = _T("toolbarMenuFriends");
const String kToolbarMenuNetworks = _T("toolbarMenuNetworks");
const String kToolbarMenuInbox = _T("toolbarMenuInbox");
const String kToolbarMenuPhotos = _T("toolbarMenuPhotos");
const String kToolbarMenuNotes = _T("toolbarMenuNotes");
const String kToolbarMenuGroups = _T("toolbarMenuGroups");
const String kToolbarMenuEvents = _T("toolbarMenuEvents");
const String kToolbarMenuPostedItems = _T("toolbarMenuPostedItems");
const String kToolbarMenuAccount = _T("toolbarMenuAccount");
const String kToolbarMenuPrivacy = _T("toolbarMenuPrivacy");
const String kToolbarMenuLanguage = _T("toolbarMenuLanguage");
const String kToolbarMenuToolbarSettings = _T("toolbarMenuToolbarSettings");

//html views
const String kHtmlNoFriendsToShow = _T("htmlNoFriendsToShow");
const String kHtmlPressEnterToFindFriend = _T("htmlPressEnterToFindFriend");
const String kHtmlLoginFromTheToolbar = _T("htmlLoginFromTheToolbar");
const String kHtmlSeeAllFriends = _T("htmlSeeAllFriends");
const String kHtmlLoadingFriendsList = _T("htmlLoadingFriendsList");

// login
const String kLoginLoginToFacebook = _T("loginLoginToFacebook");
const String kLoginCloseLoginWindow = _T("loginCloseLoginWindow");

// notifications
const String kNotifierFacebookNotification = _T("notifierFacebookNotification");
const String kNotifierYourStatusWasCleared = _T("notifierYourStatusWasCleared");
const String kNotifierYourStatusWasSet = _T("notifierYourStatusWasSet");
const String kNotifierYouHaveANewMessage = _T("notifierYouHaveANewMessage");
const String kNotifierYouHaveNewMessages = _T("notifierYouHaveNewMessages");

const String kNotifierYouHaveBeenPoked = _T("notifierYouHaveBeenPoked");
const String kNotifierYouHaveBeenPokedTimes = _T("notifierYouHaveBeenPokedTimes");
const String kNotifierYouHaveBeenPokedManyTimes = _T("notifierYouHaveBeenPokedManyTimes");

const String kNotifierSmWantsToBeYourFriend = _T("notifierSmWantsToBeYourFriend");
const String kNotifierSmAddedNewPhotosTo = _T("notifierSmAddedNewPhotosTo");
const String kNotifierSmCreatedTheAlbum = _T("notifierSmCreatedTheAlbum");

const String kNotifierSmWroteOnYourWall = _T("notifierSmWroteOnYourWall");
const String kNotifierSmIsNowYourFriend = _T("notifierSmIsNowYourFriend");
const String kNotifierSmWroteOnSmWall = _T("notifierSmWroteOnSmWall");
const String kNotifierSmUpdatedHisHerProfile = _T("notifierSmUpdatedHisHerProfile");
const String kNotifierSmWroteANote = _T("notifierSmWroteANote");
const String kNotifierNewVersion = _T("notifierNewVersion");
const String kNotifierYesDescription = _T("notifierYesDescription");
const String kNotifierNoDescription = _T("notifierNoDescription");
const String kNotifierDoNotAskMeAgain = _T("notifierDoNotAskMeAgain");

const String kHtmlMessage = _T("htmlMessage");
const String kHtmlPoke = _T("htmlPoke");
const String kHtmlWallPost = _T("htmlWallPost");

const String kHtmlPopupMessage = _T("htmlPopupMessage");
const String kHtmlPopupPoke = _T("htmlPopupPoke");
const String kHtmlPopupWallPost = _T("htmlPopupWallPost");

const String kNoUpdates  = _T("statusNoUpdates");
const String kUpdateInProgress  = _T("statusUpdateInProgress");
const String kUpdateAvailable  = _T("statusUpdateAvailable");

const String kNotifierDownloadNewUpdates = _T("notifierDownloadNewUpdates");
const String kNotifierInstallNewUpdates = _T("notifierInstallNewUpdates");

const String kMonday = _T("Monday");
const String kTuesday = _T("Tuesday");
const String kWednesday = _T("Wednesday");
const String kThursday = _T("Thursday");
const String kFriday = _T("Friday");
const String kSaturday = _T("Saturday");
const String kSunday = _T("Sunday");
const String kYesterday = _T("Yesterday");
const String kYesterdaySmall = _T("YesterdaySmall");
const String kToday = _T("Today");
const String kTodaySmall = _T("TodaySmall");

const String kAboutWeekAgoSmall = _T("AboutWeekAgoSmall");
const String kAboutTwoWeekAgoSmall = _T("AboutTwoWeekAgoSmall");
const String kAboutWeekAgoParam = _T("AboutWeekAgoParam");
const String kAboutMonthAgoSmall = _T("AboutMonthAgoSmall");
const String kDateTimeFormat = _T("DateTimeFormat");
const String kWeekDateTimeFormat = _T("WeekDateTimeFormat");
const String kProfileTimeFormat = _T("ProfileTimeFormat");
const String kProfileWeekTimeFormat = _T("ProfileWeekTimeFormat");

} // !namespace facebook

#endif