//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FBIEToolbar.rc
//
#define IDR_BMP_TLBHOT                  111
#define IDR_BMP_TOOLBAR_HOT             111
#define IDB_BITMAP_TOOLBAR              113
#define IDR_BMP_TOOLBAR                 113
#define IDR_TLB_FBIETOOLS               114
#define IDB_BITMAP1                     115
#define IDR_DFAULT_USER                 115
#define ID_BUTTON_APP                   116
#define IDR_MENU_POPUP                  117
#define IDR_HTML1                       117
#define IDB_IETOOLBAR_BUTTONS           117
#define IDB_IETOOLBAR_HOT_BUTTONS       118
#define IDR_FRIENDS_LIST_XSL            120
#define IDB_BITMAP3                     120
#define IDR_HTML_NOTIFIER               121
#define IDS_SORT_BY_LAST_UPDATE_TIME    121
#define IDB_BITMAP2                     121
#define IDB_SMALL_LOGO                  121
#define IDS_SORT_BY_STATUS_UPDATE_TIME  122
#define IDS_SORT_BY_PROFILE_UPDATE      123
#define IDS_SORT_BY_PROFILE_UPDATE_TIME 123
#define IDS_SORT_BY_NAME                124
#define IDS_TBI_SETTINGS                125
#define IDS_SEARCH_BANNER               126
#define IDD_DLG_CONFIGURE               127
#define IDD_CONFIGURE                   127
#define IDS_USERSTATUS_BANNER           127
#define IDS_USERSTATUS_DEFAULT_TEXT     128
#define IDS_QUICKLINKS_CAPTION          129
#define IDS_QUICKLINKS_BUTTON_CAPTION   129
#define IDS_LOGIN_BUTTON_CAPTION        130
#define IDS_LOGOUT_BUTTON_CAPTION       131
#define IDS_COUNTITEM_INVALIDTEXT       132
#define IDS_STRING133                   133
#define IDS_HTML_NO_FRIEND_TO_SHOW      134
#define IDS_MESSAGE_NO_FRIEND_TO_SHOW   134
#define IDS_MESSAGE_PRESS_ENTER_TO_FIND 135
#define IDR_POPUP_FRIEND_LIST_XSLT      136
#define IDS_MESSAGE_PLEASE_LOGIN        136
#define IDS_MESSAGE_SEE_ALL_FRIENDS     137
#define IDR_SIDEBAR_FRIEND_LIST_XSLT    138
#define IDS_MESSAGE_LOADING_FRIENDS_LIST 138
#define IDD_UPDATEURLPROMPT             139
#define IDB_SHARE_PLUS                  142
#define IDB_SHARE_HOT_PLUS              143
#define IDR_SIDEBAR_FRIEND_LIST_RTL_XSLT 144
#define IDR_HTML2                       145
#define IDR_TOOLBAR_CSS_RTL             145
#define IDB_IETOOLBAR_BUTTONS_RTL       146
#define IDB_IETOOLBAR_HOT_BUTTONS_RTL   147
#define IDC_CHK_POPUP_NOTIF             1001
#define IDC_CHK_NFRIEND_REQ             1002
#define IDC_CHK_NMESSAGE                1003
#define IDC_TBI_SORT_BY                 1003
#define IDC_CHK_NPOKE                   1004
#define IDSETTINGS                      1004
#define IDC_TBI_SETTINGS                1004
#define IDC_CHK_NFRIEND                 1005
#define IDC_CHK_NEVENT_INV              1006
#define IDC_CHK_GROUP_INV               1007
#define IDC_CHK_NSHARE                  1008
#define IDC_CHK_SWROTE_WALL             1009
#define IDC_CHK_AFU_PROFILE             1010
#define IDC_CHK_AFU_STATUS              1011
#define IDC_CHK_AFU_ALBUMS              1012
#define IDC_CHK_AFU_WALL                1013
#define IDC_CHK_AF_NOTE                 1014
#define IDC_BTN_CUSTOMIZE               1015
#define IDC_STATIC_GR2                  1015
#define IDC_STATIC_GR1                  1016
#define IDC_CHK_POPUP_NOTIF2            1017
#define IDC_CHK_UPDATES                 1017
#define IDC_PREIX_EDIT                  1018
#define IDC_PREFIX_EDIT                 1018
#define IDC_UPDATE_STATUS               1019
#define ID_QL_PROFILE                   40001
#define ID_BTNTB_QUICKLINKS             40001
#define ID_BUTTON40002                  40002
#define ID_QL_FRIENDS                   40002
#define ID_BTNTB_HOME                   40002
#define ID_BUTTON40003                  40003
#define ID_QL_NETWORKS                  40003
#define ID_BTNTB_NEWPOKES               40003
#define ID_BUTTON40004                  40004
#define ID_QL_INBOX                     40004
#define ID_BTN_NEWFRREQ                 40004
#define ID__PROFILE                     40005
#define ID_QL_PTHOTOS                   40005
#define ID__FRIENDS                     40006
#define ID_QL_PHOTOS                    40006
#define ID__NETWORKS                    40007
#define ID_QL_NOTES                     40007
#define ID__INBOX                       40008
#define ID_QL_GROUPS                    40008
#define ID__                            40009
#define ID_QL_EVENTS                    40009
#define ID__NOTES                       40010
#define ID_QL_POSTEDITEMS               40010
#define ID__GROUPS                      40011
#define ID_QL_ACCOUNT                   40011
#define ID__EVENTS                      40012
#define ID_QL_PRIVACY                   40012
#define ID__POSTEDITEMS                 40013
#define ID_QL_TOOLBARSETTINGS           40013
#define ID__ACCOUNT                     40014
#define ID__PRIVACY                     40015
#define ID__TOOLBARSETTINGS             40016
#define ID_BUTTON40017                  40017
#define ID_BTN_NEWMESSAGE               40017
#define ID_BUTTON40018                  40018
#define ID_BTNTB_NEI                    40018
#define ID_BUTTON40019                  40019
#define ID_BTNTB_NGI                    40019
#define ID_SORT_LAST_UPDATE_TIME        40022
#define ID_SORT_STATUS_UPDATE_TIME      40023
#define ID_SORT_PROFILE_UPDATE_TIME     40024
#define ID_SORT_NAME                    40025
#define IDR_TDEFAULT                    40029
#define IDR_TOOLBAR_CSS                 40030
#define IDR_TOOLBAR_JS                  40031
#define IDR_MESSAGE_VIEW                40032
#define IDR_ONE_FRIEND_VIEW             40033
#define IDR_POPUP_VIEW                  40034
#define IDR_SIDEBAR_VIEW                40035
#define IDR_LIB_JS                      40036
#define ID_QUICKLINKS_LANGUAGE          40037
#define ID_LANGUAGE_ENGLISH             40038
#define IDR_LANGUAGE_FILE               45000
#define ID_LANGUAGE                     45000
#define IDC_TBI_SIDEBAR                 50001
#define IDC_TBI_SEARCH                  50002
#define IDC_TBI_QUICKLINKS              50003
#define IDC_TBI_HOME                    50004
#define IDC_TBI_POKES                   50005
#define IDC_TBI_REQUESTS                50006
#define IDC_TBI_MESSAGES                50007
#define IDC_TBI_EVENTINVS               50008
#define IDC_TBI_GROUPINVS               50009
#define IDC_TBI_SHARE                   50010
#define IDC_TBI_PROFILE                 50011
#define IDC_TBI_STATUS                  50012
#define IDC_TBI_LOGIN                   50013
#define IDC_TBI_LOGOUT                  50014
#define IDC_TBI_SEPARATOR               50015

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         40040
#define _APS_NEXT_CONTROL_VALUE         1020
#define _APS_NEXT_SYMED_VALUE           123
#endif
#endif
